using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using TravelExpert_ThreadedProject3.Models;

namespace TravelExpert_ThreadedProject3
{
    public partial class AddMoifyPackageForm : Form
    {
        public Package Package { get; set; }
        public bool AddPackage { get; set; }

        public AddMoifyPackageForm()
        {
            InitializeComponent();
        }

        private void AddMoifyPackageForm_Load(object sender, EventArgs e)
        {
            if (AddPackage)
            {
                this.Text = "Add Package";
                textBox_Id.ReadOnly = true;
            }
            else
            {
                this.Text = "Edit Package";
                textBox_Id.ReadOnly = true;
                this.DisplayPackage();
            }
        }

        private void DisplayPackage()
        {
            textBox_Id.Text = Package.PackageId.ToString();
            textBox_Name.Text = Package.PkgName;
            dateTimePicker_StartD.Text = Package.PkgStartDate.ToString();
            dateTimePicker_EndD.Text = Package.PkgEndDate.ToString();
            textBox_Desc.Text = Package.PkgDesc;
            textBox_BaseP.Text = Package.PkgBasePrice.ToString("N2");
            textBox_Comm.Text = Package.PkgAgencyCommission?.ToString("N2");

        }

        private void button_Accept_Click(object sender, EventArgs e)
        {
            if (IsValidData())
            {
                if (AddPackage)
                {
                    this.Package = new Package();
                }
                this.LoadPackageData();
                this.DialogResult = DialogResult.OK;
            }
        }

        private bool IsValidData()
        {
            bool success = true;
            string errorMessage = "";

            errorMessage += Validator.IsPresent(textBox_Name.Text, textBox_Name.Tag.ToString());
            errorMessage += Validator.IsPresent(dateTimePicker_StartD.Text, dateTimePicker_StartD.Tag.ToString());
            errorMessage += Validator.IsPresent(dateTimePicker_EndD.Text, dateTimePicker_EndD.Tag.ToString());
            errorMessage += Validator.IsPresent(textBox_Desc.Text, textBox_Desc.Tag.ToString());
            errorMessage += Validator.IsPresent(textBox_BaseP.Text, textBox_BaseP.Tag.ToString());
            errorMessage += Validator.IsDecimal(textBox_BaseP.Text, textBox_BaseP.Tag.ToString());
            errorMessage += Validator.IsPresent(textBox_Comm.Text, textBox_Comm.Tag.ToString());
            errorMessage += Validator.IsDecimal(textBox_Comm.Text, textBox_Comm.Tag.ToString());
            errorMessage += Validator.IsStartEndDate(dateTimePicker_StartD.Text, dateTimePicker_EndD.Text);
            errorMessage += Validator.IsCommission(textBox_BaseP.Text, textBox_Comm.Text);

            if (errorMessage != "")
            {
                success = false;
                MessageBox.Show(errorMessage, "Entry Error");
            }
            return success;

        }

        private void LoadPackageData()
        {
            //Package.PackageId = Convert.ToInt32(textBox_Id.Text); //This is autogenerated
            Package.PkgName = textBox_Name.Text;
            Package.PkgStartDate = dateTimePicker_StartD.Value;
            Package.PkgEndDate = dateTimePicker_EndD.Value;
            Package.PkgDesc = textBox_Desc.Text;
            Package.PkgBasePrice = Convert.ToDecimal(textBox_BaseP.Text);
            Package.PkgAgencyCommission = Convert.ToDecimal(textBox_Comm.Text);


        }
    }
}
